#!/usr/bin/env python
# coding: utf-8

# (w90-nb)=
# # Wannier90 example with silicon

# In[1]:


from pythtb import W90
import matplotlib.pyplot as plt
import numpy as np


# In[2]:


silicon = W90("silicon_w90", "si")


# In[3]:


# hard coded fermi level in eV
fermi_ev = 6.2285135


# In[4]:


# all pair distances between the orbitals
print("Shells:\n", silicon.shells())


# We can look at how the Hamiltonian matrix elements generated by Wannier90 decay with distance. This will help us determine the cutoff radius to use in a tight-binding model constructed with `pythtb`. Most hoppings are above $1$ meV within a radius of about 10 Å, so we will use this as our curtoff energy in this example.

# In[5]:


# plot hopping terms as a function of distance on a log scale
(dist, ham) = silicon.dist_hop()
fig, ax = plt.subplots()
ax.scatter(dist, np.abs(ham))
ax.hlines(
    1e-3, xmin=0, xmax=max(dist), colors="r", linestyles="dashed", label="Cutoff = 1meV"
)
ax.legend()
ax.set_xlabel("Distance (A)")
ax.set_ylabel(r"$H$ (eV)")
ax.set_yscale("log")


# Now, we will generate the tight-binding model for silicon using the Wannier90 output files. This will use the Hamiltonian matrix elements generated by Wannier90 to create a `TBModel` object in `pythtb`.
#
# :::{tip}
# It is advised to save the tight-binding model to disk with the cPickle module:
# ```python
# import cPickle
# cPickle.dump(my_model, open("store.pkl", "wb"))
# ```
# Later one can load in the model from disk in a separate script with
# ```python
# my_model = cPickle.load(open("store.pkl", "rb"))
# ```
# :::

# In[6]:


# get tb model in which some small terms are ignored
my_model = silicon.model(
    zero_energy=fermi_ev,
    # min_hopping_norm=1e-10,
    # max_distance=None,
    # ignorable_imaginary_part=None,
)


# In[7]:


my_model.norb


# # Band comparison

# First, we will obtain the band structure from the Wannier90 calculation. To do this, we call the `W90.w90_bands` function, which reads the `si_band.dat`, `si_band.kpt` and `si.win` files to extract the band energies and k-point path used in the Wannier90 calculation. Setting `return_k_node_dist=True` returns the cumulative distance along the k-point path through the high-symmetry points, which we will use later for plotting. Setting `return_k_nodes = True` returns the fractional coordinates of the high-symmetry k-points along the path, as well as their labels.
#
# :::{hint}
# Small discrepancies in the plot may arise due to the terms that were ignored in the silicon.model function call above.
# :::

# In[8]:


w90_kpt, w90_evals, w90_k_dist, w90_k_nodes, w90_k_labels = silicon.w90_bands(
    return_k_dist=True, return_k_nodes=True
)


# In[9]:


w90_k_nodes


# In[10]:


w90_k_labels


# For plotting purposes, we also need to know the cumulative distance along the k-point path at each high-symmetry k-point node, which we compute below.

# In[11]:


k_vec, k_dist, k_node_dist = my_model.k_path(w90_k_nodes, nk=500, report=False)


# Next, we will solve and plot the `TBModel` on the same path as used in Wannier90. This allows us to directly compare the two band structures.

# In[12]:


int_evals = my_model.solve_ham(w90_kpt)


# In[13]:


fig, ax = plt.subplots(figsize=(10, 6))

ax.plot(w90_k_dist, w90_evals[:, 0] - fermi_ev, "k-", zorder=0, label="Wannier90")
ax.plot(w90_k_dist, w90_evals[:, 1:] - fermi_ev, "k-", zorder=0)
ax.plot(w90_k_dist, int_evals[:, 0], "r--", zorder=1, label="TBModel")
ax.plot(w90_k_dist, int_evals[:, 1:], "r--", zorder=1)

# set x-ticks at k-point nodes
ax.set_xticks(k_node_dist)
for n in range(len(w90_k_nodes)):
    ax.axvline(x=k_node_dist[n], linewidth=0.5, color="k", zorder=1)
ax.set_xticklabels(w90_k_labels, size=12)
ax.set_xlim(k_node_dist[0], k_node_dist[-1])
ax.set_ylabel("Band energy (eV)")
plt.show()


# In[2]:


#!/usr/bin/env python

# Copyright under GNU General Public License 2010, 2012, 2016
# by Sinisa Coh and David Vanderbilt (see gpl-pythtb.txt)

from __future__ import print_function
from pythtb import *  # import TB model class
import matplotlib.pyplot as plt

# read output from Wannier90 that should be in folder named "example_a"
# see instructions above for how to obtain the example output from Wannier90
# for testing purposes
silicon = w90(r"silicon_w90", r"si")

# hard coded fermi level in eV
fermi_ev = 0.62285135e01

# all pair distances berween the orbitals
print("Shells:\n", silicon.shells())

# plot hopping terms as a function of distance on a log scale
(dist, ham) = silicon.dist_hop()
fig, ax = plt.subplots()
ax.scatter(dist, np.log(np.abs(ham)))
ax.set_xlabel("Distance (A)")
ax.set_ylabel(r"$\log H$ (eV)")
fig.tight_layout()
fig.savefig("silicon_dist_ham.pdf")

# get tb model in which some small terms are ignored
my_model = silicon.model(zero_energy=fermi_ev)

# in the case that all steps up to now take a lot of computer time
# it is advised to save tb model to disk with cPickle module:
#   import cPickle
#   cPickle.dump(my_model,open("store.pkl","wb"))
# Later one can load in the model from disk in a separate script with
#   my_model=cPickle.load(open("store.pkl","rb"))

# solve and plot on the same path as used in wannier90
# small discrepancy in the plot is there because of the terms that
# were ignore in the silicon.model function call above
#
fig, ax = plt.subplots()
(w90_kpt, w90_evals) = silicon.w90_bands_consistency()
for i in range(w90_evals.shape[0]):
    ax.plot(list(range(w90_evals.shape[1])), w90_evals[i] - fermi_ev, "k-", zorder=-100)
# now interpolate from the model on the same path in k-space
int_evals = my_model.solve_all(w90_kpt)
for i in range(int_evals.shape[0]):
    ax.plot(list(range(int_evals.shape[1])), int_evals[i], "r-", zorder=-50)
ax.set_xlim(0, int_evals.shape[1] - 1)
ax.set_xlabel("K-path from Wannier90")
ax.set_ylabel("Band energy (eV)")
fig.tight_layout()
# fig.savefig("silicon.pdf")
