name: pythtb-env
channels:
  - conda-forge
dependencies:
  - python=3.12

  # core
  - numpy
  - matplotlib
  - plotly

  # jupyter
  - jupyterlab
  - ipykernel
  - notebook
  - jupyter_client
  - nbclient
  - jupyter-server-proxy

  # pip only for things you truly need from pip
  - pip
  - pip:
      # install your repo so tutorials can import it
      - -e .

      # docs tooling (OK via pip, but many are also available on conda-forge)
      - sphinx
      - pydata-sphinx-theme
      - sphinx-copybutton
      - myst-nb
      - sphinxcontrib-programoutput
      - nbconvert
      - sphinx_design
      - sphinx_thebe
